#pragma once
//engine header
#include "Log.h"
#include "Memory.h"
#include "MemoryPool.h"
#include "MathDefs.h"
#include "Resource.h"
#include <stdio.h>

//std header
#include <vector>
#include <string>
#include <unordered_map>
#include <sstream>
#include <iostream>
#include <fstream>
#include <io.h>
#include <algorithm>
#include <bgfx.h>
#include <bx/fpumath.h>
#include <bx/bx.h>
#include <bx/commandline.h>
#include "DataDef.h"
#include "ShaderInc.h"
#include "Utils.h"
