echo exporting run animations
MayaBatchTool.exe 1_Run_Forward.mb 4 monk/animations/monk_run_0.hkx
MayaBatchTool.exe 1_Run_Forward_Left.mb 5 monk/animations/monk_run_left.hkx
MayaBatchTool.exe 1_Run_Forward_Right.mb 5 monk/animations/monk_run_right.hkx
MayaBatchTool.exe 1_Run_Right_Turn_180.mb 5 monk/animations/monk_run_180.hkx
MayaBatchTool.exe 1_Stand_To_Run.mb 4 monk/animations/monk_stand_to_run_0.hkx
MayaBatchTool.exe 1_Stand_To_Run_Right_45.mb 5 monk/animations/monk_stand_to_run_45.hkx
MayaBatchTool.exe 1_Stand_To_Run_Right_90.mb 5 monk/animations/monk_stand_to_run_90.hkx
MayaBatchTool.exe 1_Stand_To_Run_Right_135.mb 5 monk/animations/monk_stand_to_run_135.hkx
MayaBatchTool.exe 1_Stand_To_Run_Right_180.mb 5 monk/animations/monk_stand_to_run_180.hkx
